export const interestGroups = [
  {
    id: "sea",
    title: "แหล่งท่องเที่ยวทางทะเล",
    image: require("@/assets/interests/sea.jpg"),
    items: [
      { id: "beach", label: "ชายหาดทราย" },
      { id: "island", label: "เกาะกลางทะเล" },
      { id: "bay", label: "อ่าวน้ำใส" },
      { id: "coral", label: "แนวปะการัง" },
      { id: "sea_viewpoint", label: "จุดชมวิวทะเล" },
    ],
  },
  {
    id: "mountain",
    title: "แหล่งท่องเที่ยวภูเขา",
    image: require("@/assets/interests/mountain.jpg"),
    items: [
      { id: "peak", label: "ยอดเขา" },
      { id: "mist_view", label: "จุดชมวิวทะเลหมอก" },
      { id: "cliff", label: "หน้าผาสูง" },
      { id: "valley", label: "หุบเขาลึก" },
      { id: "mountain_trail", label: "เส้นทางขึ้นเขา" },
    ],
  },
  {
    id: "forest",
    title: "แหล่งท่องเที่ยวธรรมชาติ",
    image: require("@/assets/interests/forest.jpg"),
    items: [
      { id: "rainforest", label: "ป่าดิบชื้น" },
      { id: "waterfall", label: "น้ำตกธรรมชาติ" },
      { id: "national_park", label: "อุทยานแห่งชาติ" },
      { id: "nature_trail", label: "เส้นทางศึกษาธรรมชาติ" },
      { id: "wildlife_zone", label: "พื้นที่อนุรักษ์สัตว์ป่า" },
    ],
  },
  {
    id: "culture",
    title: "แหล่งท่องเที่ยวเชิงวัฒนธรรม",
    image: require("@/assets/interests/culture.jpg"),
    items: [
      { id: "temple", label: "วัดสำคัญ" },
      { id: "heritage", label: "โบราณสถาน" },
      { id: "old_town", label: "เมืองเก่า" },
      { id: "cultural_site", label: "แหล่งมรดก" },
      { id: "architecture", label: "สถาปัตยกรรม" },
    ],
  },
  {
    id: "city",
    title: "แหล่งท่องเที่ยวในเมืองไลฟ์สไตล์",
    image: require("@/assets/interests/city.jpg"),
    items: [
      { id: "landmark", label: "แลนด์มาร์กเมือง" },
      { id: "business_area", label: "ย่านธุรกิจ" },
      { id: "walking_street", label: "ถนนคนเดิน" },
      { id: "cafe", label: "ย่านคาเฟ่" },
      { id: "shopping_center", label: "ศูนย์การค้า" },
    ],
  },
  {
    id: "food",
    title: "แหล่งท่องเที่ยวด้านอาหารท้องถิ่น",
    image: require("@/assets/interests/food.jpg"),
    items: [
      { id: "food_market", label: "ตลาดอาหาร" },
      { id: "local_restaurant", label: "ร้านอาหารท้องถิ่น" },
      { id: "seafood", label: "ร้านอาหารทะเล" },
      { id: "dessert", label: "ร้านของหวาน" },
      { id: "famous_food", label: "ร้านอาหารชื่อดัง" },
    ],
  },
  {
    id: "wellness",
    title: "แหล่งท่องเที่ยวเชิงสุขภาพ",
    image: require("@/assets/interests/relax.jpg"),
    items: [
      { id: "wellness_resort", label: "รีสอร์ทสุขภาพ" },
      { id: "hot_spring", label: "บ่อน้ำพุร้อน" },
      { id: "meditation", label: "สถานปฏิบัติธรรม" },
      { id: "spa", label: "สปาธรรมชาติ" },
      { id: "peaceful_place", label: "สถานที่เงียบสงบ" },
    ],
  },
  {
    id: "night_market",
    title: "แหล่งท่องเที่ยวกลางคืน ย่านบันเทิง",
    image: require("@/assets/interests/night.jpg"),
    items: [
      { id: "night_market", label: "ตลาดกลางคืน" },
      { id: "night_walking_street", label: "ถนนคนเดินกลางคืน" },
      { id: "bar_area", label: "ย่านบาร์" },
      { id: "club_area", label: "ย่านคลับ" },
      { id: "live_music", label: "แหล่งแสดงดนตรีสด" },
    ],
  },
  {
    id: "art",
    title: "แหล่งท่องเที่ยวด้านศิลปะ",
    image: require("@/assets/interests/art.jpg"),
    items: [
      { id: "art_museum", label: "พิพิธภัณฑ์ศิลปะ" },
      { id: "gallery", label: "แกลเลอรี่" },
      { id: "street_art", label: "งาน street art" },
      { id: "design_center", label: "ศูนย์ออกแบบ" },
      { id: "exhibition", label: "นิทรรศการ" },
    ],
  },
  {
    id: "rural",
    title: "แหล่งท่องเที่ยวชนบท วิถีชีวิตท้องถิ่น",
    image: require("@/assets/interests/rural.jpg"),
    items: [
      { id: "village", label: "หมู่บ้านชุมชน" },
      { id: "farm", label: "ฟาร์มเกษตร" },
      { id: "local_market", label: "ตลาดพื้นบ้าน" },
      { id: "local_life", label: "วิถีชาวบ้าน" },
      { id: "community_tourism", label: "แหล่งท่องเที่ยวชุมชน" },
    ],
  },
];